package com.mc.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVmoodComment<M extends BaseVmoodComment<M>> extends Model<M> implements IBean {

	public void setMoodId(java.lang.Integer moodId) {
		set("mood_id", moodId);
	}

	public java.lang.Integer getMoodId() {
		return get("mood_id");
	}

	public void setMoodContent(java.lang.String moodContent) {
		set("mood_content", moodContent);
	}

	public java.lang.String getMoodContent() {
		return get("mood_content");
	}

	public void setMoodCreatetime(java.util.Date moodCreatetime) {
		set("mood_createtime", moodCreatetime);
	}

	public java.util.Date getMoodCreatetime() {
		return get("mood_createtime");
	}

	public void setMoodPrivacy(java.lang.Integer moodPrivacy) {
		set("mood_privacy", moodPrivacy);
	}

	public java.lang.Integer getMoodPrivacy() {
		return get("mood_privacy");
	}

	public void setMoodAgree(java.lang.String moodAgree) {
		set("mood_agree", moodAgree);
	}

	public java.lang.String getMoodAgree() {
		return get("mood_agree");
	}

	public void setMoodUid(java.lang.Integer moodUid) {
		set("mood_uid", moodUid);
	}

	public java.lang.Integer getMoodUid() {
		return get("mood_uid");
	}

	public void setMoodUnikename(java.lang.String moodUnikename) {
		set("mood_unikename", moodUnikename);
	}

	public java.lang.String getMoodUnikename() {
		return get("mood_unikename");
	}

	public void setMoodUusername(java.lang.String moodUusername) {
		set("mood_uusername", moodUusername);
	}

	public java.lang.String getMoodUusername() {
		return get("mood_uusername");
	}

	public void setCommentId(java.lang.Integer commentId) {
		set("comment_id", commentId);
	}

	public java.lang.Integer getCommentId() {
		return get("comment_id");
	}

	public void setCommentCuid(java.lang.Integer commentCuid) {
		set("comment_cuid", commentCuid);
	}

	public java.lang.Integer getCommentCuid() {
		return get("comment_cuid");
	}

	public void setCommentCunikename(java.lang.String commentCunikename) {
		set("comment_cunikename", commentCunikename);
	}

	public java.lang.String getCommentCunikename() {
		return get("comment_cunikename");
	}

	public void setCommentCuusername(java.lang.String commentCuusername) {
		set("comment_cuusername", commentCuusername);
	}

	public java.lang.String getCommentCuusername() {
		return get("comment_cuusername");
	}

	public void setCommentContent(java.lang.String commentContent) {
		set("comment_content", commentContent);
	}

	public java.lang.String getCommentContent() {
		return get("comment_content");
	}

	public void setCommentCreatetime(java.util.Date commentCreatetime) {
		set("comment_createtime", commentCreatetime);
	}

	public java.util.Date getCommentCreatetime() {
		return get("comment_createtime");
	}

	public void setCommentType(java.lang.Integer commentType) {
		set("comment_type", commentType);
	}

	public java.lang.Integer getCommentType() {
		return get("comment_type");
	}

	public void setCommentBuid(java.lang.Integer commentBuid) {
		set("comment_buid", commentBuid);
	}

	public java.lang.Integer getCommentBuid() {
		return get("comment_buid");
	}

	public void setCommentBunikename(java.lang.String commentBunikename) {
		set("comment_bunikename", commentBunikename);
	}

	public java.lang.String getCommentBunikename() {
		return get("comment_bunikename");
	}

	public void setCommentBuusername(java.lang.String commentBuusername) {
		set("comment_buusername", commentBuusername);
	}

	public java.lang.String getCommentBuusername() {
		return get("comment_buusername");
	}

}
