package com.mc.base.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("comment", "id", Comment.class);
		arp.addMapping("contacts", "id", Contacts.class);
		arp.addMapping("groups", "id", Groups.class);
		arp.addMapping("mood", "id", Mood.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("websites", "id", Websites.class);
		arp.addMapping("vmood_comment", "", VmoodComment.class);
	}
}

