package com.mc.base.model;

import com.mc.base.BaseContacts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contacts extends BaseContacts<Contacts> {
	public static final Contacts dao = new Contacts();
}
