package com.mc.base.model;

import com.mc.base.BaseGroups;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Groups extends BaseGroups<Groups> {
	public static final Groups dao = new Groups();
}
