package com.mc.base.model;

import com.mc.base.BaseMood;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mood extends BaseMood<Mood> {
	public static final Mood dao = new Mood();
}
