package com.mc.base.model;

import com.mc.base.BaseVmoodComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VmoodComment extends BaseVmoodComment<VmoodComment> {
	public static final VmoodComment dao = new VmoodComment();
}
