package com.mc.base.model;

import com.mc.base.BaseWebsites;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Websites extends BaseWebsites<Websites> {
	public static final Websites dao = new Websites();
}
